module.exports = {
    "getPropertyIE": "viewIncomeExpense",
    "dataReductionIE":"viewIncomeExpense",
    "propertyValuationIE": "viewIncomeExpense",
    "addPropertyIE": "attachFilesToProperty",
    "addPropertyIEManual": "attachFilesToProperty",
    "addBulkPropertyIE": "attachFilesToProperty",
    "unlinkIEFiles": "unlinkPropertyData",
    "uploadOtherFiles": "attachFilesToProperty",
    "unlinkOtherFilesById": "unlinkPropertyData",
    "addImages": "editPropertyImage",
    "setMainImage": "editPropertyImage",
    "getAllImages": "editPropertyImage",
    "getMainImage": "editPropertyImage",
    "deleteImageById": "editPropertyImage",
    "addPropertyRR": "attachFilesToProperty",
    "addPropertyRRManual": "attachFilesToProperty",
    "addBulkPropertyRR": "attachFilesToProperty",
    "getPropertyRR": "viewRentRolls",
    "getPropertyRRUnits": "viewRentRolls",
    "unlinkRentRollsById": "unlinkPropertyData",
    "getSavedComps": "viewComparables",    
    "getComparables": "viewComparables",
    "uploadTaxBillFile": "attachFilesToProperty",
    "viewTaxBills": "attachFilesToProperty",
    "unlinkTaxBillsById": "unlinkPropertyData",
    "save-form": "editValuationForm",
    "get-modal": "viewValuationForm",
    "get-evidence-files": "viewValuationForm",
    "get-evidence-by-Id": "viewValuationForm",
    "get-forms-by-propertyId": "viewValuationForm",
    "get-forms-by-formId": "viewValuationForm",
    "replace-valuation-form": "editValuationForm",
    "save-work-space": "editValuationWorkspace",
    "replace-work-space":"editValuationWorkspace",
    "get-work-space": "viewValuationWorkspace",
    "delete-valuation-form":"editValuationForm",
    "assignPropertyToAgent": "assignProperty",
    "getAssignedUsers":"assignProperty",
    "removeAssignedUser":"assignProperty"
};